### ISSUE TITLE
1.1.2 and later not available in the 2020.3 EAP marketplace

### ISSUE THREAD

**Issue by juherr** [jlagerweij/cucumber-kotlin#25]
Hi,

I'm using the following IDEA version:

> IntelliJ IDEA 2020.3 EAP (Ultimate Edition)
> Build #IU-203.4818.26, built on October 14, 2020
> IntelliJ IDEA EAP User
> Expiration date: November 13, 2020
> Runtime version: 11.0.8+10-b1129.2 x86_64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> macOS 10.15.7
> GC: ParNew, ConcurrentMarkSweep
> Memory: 1981M
> Cores: 8
> Registry: debugger.watches.in.variables=false
> Non-Bundled Plugins: com.intellij.ideolog, com.atlassian.bitbucket.references, org.sonarlint.idea, com.dmarcotte.handlebars, org.jetbrains.plugins.vue, org.asciidoctor.intellij.asciidoc, net.lagerwey.cucumber-kotlin

I had the exact same issue than #12 but it look I'm not able to install the installed version 1.1.2:

![image](https://user-images.githubusercontent.com/254697/97894939-6c278900-1d33-11eb-9895-3132f55f53d6.png)

It could be the same problem than #18

**Comment by jlagerweij** [comment]
Hi,

The reason for this is the fact that this plugin relies on the Gherkin plugin from IntelliJ. That plugin is update on each version of IntelliJ and for versions before 1.1.2 there was no restriction on which IntelliJ the plugin would work for. But there is a restriction as the plugin does not work if the API of the Gherkin plugin changes. 
So to fix that, I added a restriction for the plugin and because of that the version of the plugin needs to be updated for every release of IntelliJ.
So the reason you don't see a newer plugin version is because you are running the EAP. If you use 2020.2 you would find version 1.1.5 available.

**Comment by juherr** [comment]
I suppose that the plugin `1.1.5 or higher` has more chance to be compatible with the latest EAP than the plugin `1.1.2`, isn't it?
Is there any way to make a release for EAP versions too? Or at least a custom repository with snapshot builds? https://www.jetbrains.com/help/idea/managing-plugins.html#repos

**Comment by jlagerweij** [comment]
I published v1.1.6 to the normal IDEA plugin marketplace. They review it and it should be available in the next few days.

**Comment by jlagerweij** [comment]
It already available in the marketplace.

**Comment by juherr** [comment]
Installed! Thanks :) 👍
